from typing import Protocol

import pandas as pd

from domain.forecast import ForecastRun


class Repository(Protocol):
    """Persistence interface used by weather, alert, and map modules."""

    def initialize(self) -> None: ...

    def ping(self) -> None: ...

    def get_weather_cache(self, cache_key: str) -> pd.DataFrame | None: ...

    def set_weather_cache(self, cache_key: str, dataframe: pd.DataFrame) -> None: ...

    def get_raw_weather_cache(self, cache_key: str): ...

    def set_raw_weather_cache(self, cache_key: str, data: dict) -> None: ...

    def get_raw_weather_cache_batch(self, cache_keys: list[str]) -> dict: ...

    def save_alert(
        self, province: str, district: str, forecast_days: int, alert_text: str
    ) -> None: ...

    def get_alert(
        self, province: str, district: str, forecast_days: int
    ) -> str | None: ...

    def get_all_alerts(self, forecast_days: int) -> dict[str, dict[str, str]]: ...

    def get_alerts_batch(self, keys: list[tuple[str, str, int]]) -> dict: ...

    def purge_cache(
        self, province: str, districts: list[str], forecast_days: int
    ) -> int: ...

    def get_cache_stats(self) -> dict[str, int]: ...

    def cleanup_expired_cache(self) -> int: ...

    def get_latest_forecast_run(
        self, location_id: str, forecast_days: int
    ) -> ForecastRun | None: ...
