/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Districts
         * @description List districts, optionally limited to one province.
         */
        get: operations["list_districts_api_districts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/districts/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * District Boundaries
         * @description Boundary polygons as GeoJSON, each tagged with the district it belongs to.
         *
         *     Polygons with no district in the registry are included with a null
         *     ``district_id`` so the map has no holes.
         */
        get: operations["district_boundaries_api_districts_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/districts/{district_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * District Forecast
         * @description Latest daily forecast for a district, refreshed when it is too old.
         */
        get: operations["district_forecast_api_districts__district_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report whether the service and its dependencies are usable.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Run
         * @description Run a monitoring cycle now and return how it ended.
         *
         *     The response is 201 even when the cycle fails, because the run is recorded
         *     either way; check ``status`` and ``error``.
         */
        post: operations["trigger_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Signals
         * @description Hazard signals from the latest successful cycle.
         */
        get: operations["current_signals_api_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BoundaryCollection
         * @description A GeoJSON FeatureCollection of boundary polygons.
         */
        BoundaryCollection: {
            /** Features */
            features: components["schemas"]["BoundaryFeature"][];
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /**
         * BoundaryFeature
         * @description A GeoJSON feature for one boundary polygon.
         */
        BoundaryFeature: {
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["BoundaryProperties"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /**
         * BoundaryProperties
         * @description Properties of one boundary polygon.
         */
        BoundaryProperties: {
            /** District Id */
            district_id: string | null;
            /** Feature Id */
            feature_id: string;
            /** Name En */
            name_en: string;
            /** Province */
            province: string;
        };
        /**
         * CheckResult
         * @description Outcome of one dependency check.
         */
        CheckResult: {
            /** Message */
            message: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "fail";
        };
        /**
         * CurrentSignals
         * @description The latest successful cycle and the signals it raised.
         */
        CurrentSignals: {
            run: components["schemas"]["RunOut"] | null;
            /** Signals */
            signals: components["schemas"]["SignalOut"][];
        };
        /**
         * DailyForecast
         * @description One day of forecast for one location. Missing values are None.
         */
        DailyForecast: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Precipitation Mm */
            precipitation_mm: number | null;
            /** Precipitation Probability Pct */
            precipitation_probability_pct: number | null;
            /** Snowfall Cm */
            snowfall_cm: number | null;
            /** Temperature Max C */
            temperature_max_c: number | null;
            /** Temperature Min C */
            temperature_min_c: number | null;
            /** Uv Index Max */
            uv_index_max: number | null;
            /** Weather Code */
            weather_code: number | null;
            /** Wind Gusts Max Kmh */
            wind_gusts_max_kmh: number | null;
            /** Wind Speed Max Kmh */
            wind_speed_max_kmh: number | null;
        };
        /**
         * DistrictOut
         * @description A district in the registry.
         */
        DistrictOut: {
            /** Feature Id */
            feature_id: string | null;
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name En */
            name_en: string;
            /** Name Ur */
            name_ur: string | null;
            /** Province */
            province: string;
        };
        /**
         * ForecastOut
         * @description Daily forecast for a district, with where and when it came from.
         */
        ForecastOut: {
            /** Days */
            days: components["schemas"]["DailyForecast"][];
            /** District Id */
            district_id: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Source */
            source: string;
            /** Stale */
            stale: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Overall status plus the result of each check.
         */
        HealthResponse: {
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["CheckResult"];
            };
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "unhealthy";
        };
        /**
         * RunOut
         * @description A monitoring cycle and how it ended.
         */
        RunOut: {
            /** District Count */
            district_count: number;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Signal Count */
            signal_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Trigger */
            trigger: string;
        };
        /**
         * SignalOut
         * @description A hazard threshold reached in a district's forecast.
         */
        SignalOut: {
            /** Days Over */
            days_over: string[];
            /** District Id */
            district_id: string;
            /**
             * Expires
             * Format: date
             */
            expires: string;
            /** Hazard */
            hazard: string;
            /**
             * Level
             * @enum {string}
             */
            level: "moderate" | "severe" | "extreme";
            /** Metric */
            metric: string;
            /**
             * Onset
             * Format: date
             */
            onset: string;
            /**
             * Peak Date
             * Format: date
             */
            peak_date: string;
            /** Peak Value */
            peak_value: number;
            /** Snapshot Id */
            snapshot_id: number;
            /** Threshold */
            threshold: number;
            /** Unit */
            unit: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_districts_api_districts_get: {
        parameters: {
            query?: {
                /** @description Province name, case-insensitive */
                province?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    district_boundaries_api_districts_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundaryCollection"];
                };
            };
        };
    };
    district_forecast_api_districts__district_id__forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                district_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastOut"];
                };
            };
            /** @description Unknown district */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Forecast source unavailable and nothing stored */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    trigger_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Missing or wrong admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No admin token is configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    current_signals_api_signals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentSignals"];
                };
            };
        };
    };
}
