/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/air-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All Air Quality
         * @description Latest PM2.5 value for every district with stored air-quality data.
         */
        get: operations["all_air_quality_api_air_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alerts
         * @description Alerts, newest first. With no filters this is the full alert history.
         */
        get: operations["alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alert Detail
         * @description One alert with its evidence.
         */
        get: operations["alert_detail_api_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Districts
         * @description List districts, optionally limited to one province.
         */
        get: operations["list_districts_api_districts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/districts/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * District Boundaries
         * @description Boundary polygons as GeoJSON, each tagged with the district it belongs to.
         *
         *     Polygons with no district in the registry are included with a null
         *     ``district_id`` so the map has no holes.
         */
        get: operations["district_boundaries_api_districts_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/districts/{district_id}/air-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * District Air Quality
         * @description Latest PM2.5 forecast for one district.
         */
        get: operations["district_air_quality_api_districts__district_id__air_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/districts/{district_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * District Forecast
         * @description Latest daily forecast for a district, refreshed when it is too old.
         */
        get: operations["district_forecast_api_districts__district_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report whether the service and its dependencies are usable.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs
         * @description Monitoring cycles, newest first.
         */
        get: operations["runs_api_runs_get"];
        put?: never;
        /**
         * Trigger Run
         * @description Run a monitoring cycle now and return how it ended.
         *
         *     The response is 201 even when the cycle fails, because the run is recorded
         *     either way; check ``status`` and ``error``.
         */
        post: operations["trigger_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Detail
         * @description One monitoring cycle.
         */
        get: operations["run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description The run's event log as Server-Sent Events.
         *
         *     A finished run is replayed at once; an active run streams events as they
         *     happen. A client that reconnects with ``Last-Event-ID`` resumes after it.
         */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Signals
         * @description Hazard signals from the latest successful cycle.
         */
        get: operations["current_signals_api_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AirQualityOut
         * @description Latest daily mean PM2.5 forecast for a district.
         */
        AirQualityOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** District Id */
            district_id: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Pm2 5 Mean Ug M3 */
            pm2_5_mean_ug_m3: number | null;
        };
        /**
         * AlertDetail
         * @description An alert, plus the alert that replaced it if it was superseded.
         */
        AlertDetail: {
            /** Body En */
            body_en: string;
            /** Body Ur */
            body_ur: string | null;
            /**
             * Certainty
             * @enum {string}
             */
            certainty: "likely" | "possible";
            /** District Id */
            district_id: string;
            /** District Name */
            district_name: string;
            /** Ended At */
            ended_at: string | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /**
             * Expires
             * Format: date
             */
            expires: string;
            /** Generated By */
            generated_by: string;
            /** Hazard */
            hazard: string;
            /** Headline En */
            headline_en: string;
            /** Headline Ur */
            headline_ur: string | null;
            /** Id */
            id: number;
            /** Instructions En */
            instructions_en: string;
            /** Instructions Ur */
            instructions_ur: string | null;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Onset
             * Format: date
             */
            onset: string;
            /** Province */
            province: string;
            /** Run Id */
            run_id: number;
            /**
             * Severity
             * @enum {string}
             */
            severity: "moderate" | "severe" | "extreme";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "superseded" | "cancelled" | "expired";
            /** Superseded By Id */
            superseded_by_id: number | null;
            /** Supersedes Id */
            supersedes_id: number | null;
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "immediate" | "expected" | "future";
        };
        /**
         * AlertOut
         * @description An alert and the district it was issued for.
         */
        AlertOut: {
            /** Body En */
            body_en: string;
            /** Body Ur */
            body_ur: string | null;
            /**
             * Certainty
             * @enum {string}
             */
            certainty: "likely" | "possible";
            /** District Id */
            district_id: string;
            /** District Name */
            district_name: string;
            /** Ended At */
            ended_at: string | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /**
             * Expires
             * Format: date
             */
            expires: string;
            /** Generated By */
            generated_by: string;
            /** Hazard */
            hazard: string;
            /** Headline En */
            headline_en: string;
            /** Headline Ur */
            headline_ur: string | null;
            /** Id */
            id: number;
            /** Instructions En */
            instructions_en: string;
            /** Instructions Ur */
            instructions_ur: string | null;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Onset
             * Format: date
             */
            onset: string;
            /** Province */
            province: string;
            /** Run Id */
            run_id: number;
            /**
             * Severity
             * @enum {string}
             */
            severity: "moderate" | "severe" | "extreme";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "superseded" | "cancelled" | "expired";
            /** Supersedes Id */
            supersedes_id: number | null;
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "immediate" | "expected" | "future";
        };
        /**
         * BoundaryCollection
         * @description A GeoJSON FeatureCollection of boundary polygons.
         */
        BoundaryCollection: {
            /** Features */
            features: components["schemas"]["BoundaryFeature"][];
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /**
         * BoundaryFeature
         * @description A GeoJSON feature for one boundary polygon.
         */
        BoundaryFeature: {
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["BoundaryProperties"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /**
         * BoundaryProperties
         * @description Properties of one boundary polygon.
         */
        BoundaryProperties: {
            /** District Id */
            district_id: string | null;
            /** Feature Id */
            feature_id: string;
            /** Name En */
            name_en: string;
            /** Province */
            province: string;
        };
        /**
         * CheckResult
         * @description Outcome of one dependency check.
         */
        CheckResult: {
            /** Message */
            message: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "fail";
        };
        /**
         * CurrentSignals
         * @description The latest successful cycle and the signals it raised.
         */
        CurrentSignals: {
            run: components["schemas"]["RunOut"] | null;
            /** Signals */
            signals: components["schemas"]["SignalOut"][];
        };
        /**
         * DailyForecast
         * @description One day of forecast for one location. Missing values are None.
         */
        DailyForecast: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Precipitation Mm */
            precipitation_mm: number | null;
            /** Precipitation Probability Pct */
            precipitation_probability_pct: number | null;
            /** Snowfall Cm */
            snowfall_cm: number | null;
            /** Temperature Max C */
            temperature_max_c: number | null;
            /** Temperature Min C */
            temperature_min_c: number | null;
            /** Uv Index Max */
            uv_index_max: number | null;
            /** Weather Code */
            weather_code: number | null;
            /** Wind Gusts Max Kmh */
            wind_gusts_max_kmh: number | null;
            /** Wind Speed Max Kmh */
            wind_speed_max_kmh: number | null;
        };
        /**
         * DistrictOut
         * @description A district in the registry.
         */
        DistrictOut: {
            /** Feature Id */
            feature_id: string | null;
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name En */
            name_en: string;
            /** Name Ur */
            name_ur: string | null;
            /** Province */
            province: string;
        };
        /**
         * EvidenceOut
         * @description One forecast value that justifies an alert.
         */
        EvidenceOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Metric */
            metric: string;
            /** Snapshot Id */
            snapshot_id: number;
            /** Threshold */
            threshold: number;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /**
         * ForecastOut
         * @description Daily forecast for a district, with where and when it came from.
         */
        ForecastOut: {
            /** Days */
            days: components["schemas"]["DailyForecast"][];
            /** District Id */
            district_id: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Source */
            source: string;
            /** Stale */
            stale: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Overall status plus the result of each check.
         */
        HealthResponse: {
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["CheckResult"];
            };
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "unhealthy";
        };
        /**
         * RunEventOut
         * @description One entry in a run's event log; the ``data`` of each streamed message.
         */
        RunEventOut: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Seq */
            seq: number;
            /**
             * Type
             * @enum {string}
             */
            type: "run_started" | "step_started" | "step_finished" | "step_failed" | "source_fetched" | "signal_raised" | "error" | "run_finished";
        };
        /**
         * RunOut
         * @description A monitoring cycle and how it ended.
         */
        RunOut: {
            /** District Count */
            district_count: number;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Signal Count */
            signal_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed";
            /** Trigger */
            trigger: string;
        };
        /**
         * SignalOut
         * @description A hazard threshold reached in a district's forecast.
         */
        SignalOut: {
            /** Days Over */
            days_over: string[];
            /** District Id */
            district_id: string;
            /**
             * Expires
             * Format: date
             */
            expires: string;
            /** Hazard */
            hazard: string;
            /**
             * Level
             * @enum {string}
             */
            level: "moderate" | "severe" | "extreme";
            /** Metric */
            metric: string;
            /**
             * Onset
             * Format: date
             */
            onset: string;
            /**
             * Peak Date
             * Format: date
             */
            peak_date: string;
            /** Peak Value */
            peak_value: number;
            /** Snapshot Id */
            snapshot_id: number;
            /** Threshold */
            threshold: number;
            /** Unit */
            unit: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    all_air_quality_api_air_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirQualityOut"][];
                };
            };
        };
    };
    alerts_api_alerts_get: {
        parameters: {
            query?: {
                status?: ("active" | "superseded" | "cancelled" | "expired") | null;
                /** @description Case-insensitive */
                province?: string | null;
                hazard?: string | null;
                severity?: ("moderate" | "severe" | "extreme") | null;
                district_id?: string | null;
                issued_since?: string | null;
                issued_until?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alert_detail_api_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDetail"];
                };
            };
            /** @description Unknown alert */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_districts_api_districts_get: {
        parameters: {
            query?: {
                /** @description Province name, case-insensitive */
                province?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    district_boundaries_api_districts_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundaryCollection"];
                };
            };
        };
    };
    district_air_quality_api_districts__district_id__air_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                district_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirQualityOut"];
                };
            };
            /** @description No air-quality data */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    district_forecast_api_districts__district_id__forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                district_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastOut"];
                };
            };
            /** @description Unknown district */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Forecast source unavailable and nothing stored */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Missing or wrong admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No admin token is configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: number | null;
            };
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A stream of messages, each carrying one event as JSON, then a final message of type `end` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["RunEventOut"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_signals_api_signals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentSignals"];
                };
            };
        };
    };
}
