/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Districts
         * @description List districts, optionally limited to one province.
         */
        get: operations["list_districts_api_districts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/districts/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * District Boundaries
         * @description Boundary polygons as GeoJSON, each tagged with the district it belongs to.
         *
         *     Polygons with no district in the registry are included with a null
         *     ``district_id`` so the map has no holes.
         */
        get: operations["district_boundaries_api_districts_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report whether the service and its dependencies are usable.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BoundaryCollection
         * @description A GeoJSON FeatureCollection of boundary polygons.
         */
        BoundaryCollection: {
            /** Features */
            features: components["schemas"]["BoundaryFeature"][];
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /**
         * BoundaryFeature
         * @description A GeoJSON feature for one boundary polygon.
         */
        BoundaryFeature: {
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["BoundaryProperties"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /**
         * BoundaryProperties
         * @description Properties of one boundary polygon.
         */
        BoundaryProperties: {
            /** District Id */
            district_id: string | null;
            /** Feature Id */
            feature_id: string;
            /** Name En */
            name_en: string;
            /** Province */
            province: string;
        };
        /**
         * CheckResult
         * @description Outcome of one dependency check.
         */
        CheckResult: {
            /** Message */
            message: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "fail";
        };
        /**
         * DistrictOut
         * @description A district in the registry.
         */
        DistrictOut: {
            /** Feature Id */
            feature_id: string | null;
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name En */
            name_en: string;
            /** Name Ur */
            name_ur: string | null;
            /** Province */
            province: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Overall status plus the result of each check.
         */
        HealthResponse: {
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["CheckResult"];
            };
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "unhealthy";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_districts_api_districts_get: {
        parameters: {
            query?: {
                /** @description Province name, case-insensitive */
                province?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    district_boundaries_api_districts_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundaryCollection"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
