import type { Alert } from '../../api/client'
import { LEVEL_COLOURS, LEVEL_LABELS, hazardLabel } from '../signals/signals'

const DAY_MONTH = new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'short' })

function dayMonth(isoDate: string): string {
  const [year, month, day] = isoDate.split('-').map(Number)
  return DAY_MONTH.format(new Date(year, month - 1, day))
}

function period(alert: Alert): string {
  return alert.onset === alert.expires
    ? dayMonth(alert.onset)
    : `${dayMonth(alert.onset)} to ${dayMonth(alert.expires)}`
}

/** Opens the monitoring run that produced an alert. */
type OpenRun = (runId: number) => void

function EvidenceTable({ alert, onOpenRun }: { alert: Alert; onOpenRun?: OpenRun }) {
  return (
    <div className="mt-3 border-t border-line/25 pt-2.5">
      <p className="type-label text-ink/55">Forecast evidence</p>
      <div className="mt-1.5 overflow-x-auto">
        <table className="w-full text-left text-xs">
          <thead className="font-mono text-ink/55">
            <tr>
              <th className="pb-1 pr-2 font-normal">Date</th>
              <th className="pb-1 pr-2 font-normal">Forecast</th>
              <th className="pb-1 font-normal">Threshold</th>
            </tr>
          </thead>
          <tbody className="font-mono text-ink">
            {alert.evidence.map((evidence) => (
              <tr key={`${evidence.snapshot_id}-${evidence.metric}-${evidence.date}`}>
                <td className="py-0.5 pr-2">{dayMonth(evidence.date)}</td>
                <td className="py-0.5 pr-2">
                  {evidence.value} {evidence.unit}
                </td>
                <td className="py-0.5">
                  {evidence.threshold} {evidence.unit}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="mt-1.5 text-[0.6875rem] text-ink/50">
        Source snapshot {alert.evidence[0]?.snapshot_id ?? 'unavailable'} · generated by{' '}
        {alert.generated_by}
        {onOpenRun && (
          <>
            {' · '}
            <button
              type="button"
              onClick={() => onOpenRun(alert.run_id)}
              className="underline hover:text-ink"
            >
              Run {alert.run_id}
            </button>
          </>
        )}
      </p>
    </div>
  )
}

type CardProps = {
  alert: Alert
  compact?: boolean
  onOpenRun?: OpenRun
}

export function AlertCard({ alert, compact = false, onOpenRun }: CardProps) {
  return (
    <article className="border-l-[3px] pl-3" style={{ borderColor: LEVEL_COLOURS[alert.severity] }}>
      <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
        <span className="type-label" style={{ color: LEVEL_COLOURS[alert.severity] }}>
          {LEVEL_LABELS[alert.severity]}
        </span>
        <span className="font-mono text-[0.6875rem] text-ink/55">
          {compact && alert.status !== 'active' ? `${alert.status} · ` : ''}
          {period(alert)}
        </span>
      </div>
      <h4 className="mt-1 text-sm font-semibold leading-snug text-ink">
        {compact ? `${hazardLabel(alert.hazard)} · ${alert.district_name}` : alert.headline_en}
      </h4>
      {alert.status === 'held' && (
        <div className="mt-1.5 text-xs text-ink/75">
          <p className="font-semibold text-ink">Held: not published</p>
          <ul className="mt-0.5 list-disc pl-4">
            {(alert.held_reasons ?? []).map((reason) => (
              <li key={reason}>{reason}</li>
            ))}
          </ul>
        </div>
      )}
      {!compact && (
        <>
          <p className="mt-1.5 text-xs leading-relaxed text-ink/75">{alert.body_en}</p>
          <p className="mt-2 text-xs leading-relaxed text-ink">
            <span className="font-semibold">Safety: </span>
            {alert.instructions_en}
          </p>
          <EvidenceTable alert={alert} onOpenRun={onOpenRun} />
        </>
      )}
    </article>
  )
}

export function AlertList({ alerts, onOpenRun }: { alerts: Alert[]; onOpenRun?: OpenRun }) {
  if (alerts.length === 0) {
    return <p className="text-sm text-ink/70">No active alerts for this district.</p>
  }

  return (
    <ul className="space-y-5">
      {alerts.map((alert) => (
        <li key={alert.id}>
          <AlertCard alert={alert} onOpenRun={onOpenRun} />
        </li>
      ))}
    </ul>
  )
}
