"""Load the packaged district registry and keep the database in step with it."""

import asyncio
import json
import logging
from functools import cache
from importlib import resources
from typing import Any

from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from ews.core.db import create_engine, create_session_factory
from ews.core.settings import get_settings
from ews.districts.models import District

logger = logging.getLogger(__name__)


def _read_packaged(name: str) -> Any:
    """Read a JSON file shipped inside the package."""
    path = resources.files("ews.districts").joinpath("data", name)
    return json.loads(path.read_text(encoding="utf-8"))


@cache
def packaged_districts() -> list[dict[str, Any]]:
    """Registry rows generated by ``ews.districts.build``."""
    districts: list[dict[str, Any]] = _read_packaged("districts.json")
    return districts


@cache
def packaged_boundaries() -> dict[str, Any]:
    """Boundary FeatureCollection generated by ``ews.districts.build``."""
    boundaries: dict[str, Any] = _read_packaged("districts.geojson")
    return boundaries


async def sync_districts(session: AsyncSession) -> int:
    """Insert or update every packaged district.

    Districts are never deleted here, because other records will refer to them.

    Args:
        session: Session to write with; the caller commits

    Returns:
        Number of districts written
    """
    rows = packaged_districts()
    statement = insert(District).values(rows)
    statement = statement.on_conflict_do_update(
        index_elements=[District.id],
        set_={
            column: statement.excluded[column]
            for column in ("name_en", "name_ur", "province", "lat", "lon", "feature_id")
        },
    )
    await session.execute(statement)
    return len(rows)


async def _sync_configured_database() -> None:
    """Sync the registry into the database named by the settings."""
    engine = create_engine(get_settings().database_url)
    try:
        async with create_session_factory(engine)() as session:
            count = await sync_districts(session)
            await session.commit()
    finally:
        await engine.dispose()
    logger.info("Synced %s districts", count)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(_sync_configured_database())
